version: "3"
services:
  node:
    build: .
    container_name: reservation-app
    ports:
      - "3001:3001"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: npm start

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
